import os
import smtplib
from email.message import EmailMessage

def email_notifications_enabled() -> bool:
    return os.getenv("EMAIL_NOTIFICATIONS_ENABLED", "False").lower() == "true"

def send_case_note_notification_email(case_note) -> None:
    if not email_notifications_enabled():
        print("[EMAIL] Email notifications are disabled.")
        return

    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_username = os.getenv("SMTP_USERNAME")
    smtp_password = os.getenv("SMTP_PASSWORD")
    from_email = os.getenv("SMTP_FROM_EMAIL", smtp_username)
    to_email = os.getenv("CARE_PARTNER_EMAIL")

    if not all([smtp_username, smtp_password, from_email, to_email]):
        print("[EMAIL] SMTP configuration is incomplete. Cannot send email.")
        return

    subject = f"CareShield Notification: Case Note #{case_note.id} Generated"

    body = f"""
Hello,

A new case note has been generated in CareShield.

Case Note ID: {case_note.id}
Chat Session ID: {case_note.chat_session_id}
Incident Type: {case_note.incident_type or "N/A"}
Incident Date: {case_note.incident_date or "N/A"}
Incident Time: {case_note.incident_time or "N/A"}

Summary:
{case_note.summary}

This email was automatically generated by the CareShield prototype.

Regards,
CareShield System
"""
    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = from_email
    message["To"] = to_email
    message.set_content(body)

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_username, smtp_password)
            server.send_message(message)
        print(f"[EMAIL] Notification email sent to {to_email} for Case Note ID {case_note.id}.")
    except Exception as error:
        print(f"[EMAIL] Failed to send email notification: {error}")